Support for Magento 2.4.4 (Merging latest Vaimo bitbucket version into older github version)
vaimo/module-admin-auto-login pull request #7
Opened 2022-04-12 11:57 UTC by Nuuttif

2022-04-13 10:10 UTC, evktalo requested changes

2022-04-13 10:10 UTC, evktalo commented on CHANGELOG.md
> +- Support for Magento 2.4.4
Should be 2.4.x

2022-04-13 10:10 UTC, evktalo commented on src/Model/Config/Source/AdminUser.php
> + * See LICENSE_VAIMO.txt for license details.
This should be LICENSE since that's the filename in github

2022-04-13 10:10 UTC, evktalo commented on src/etc/adminhtml/di.xml
> + * See LICENSE_VAIMO.txt for license details.
LICENSE

2022-04-13 10:10 UTC, evktalo commented on src/etc/adminhtml/system.xml
> + * See LICENSE_VAIMO.txt for license details.
LICENSE

2022-04-13 10:10 UTC, evktalo commented on src/etc/config.xml
> + * See LICENSE_VAIMO.txt for license details.
LICENSE

2022-04-13 10:10 UTC, evktalo commented on src/etc/module.xml
> + * See LICENSE_VAIMO.txt for license details.
LICENSE

2022-04-13 10:10 UTC, evktalo commented on src/etc/module.xml
> +    <module name="Vaimo_AdminAutoLogin" setup_version="1.0.1">
I think we can drop "setup_version" since we are not installing anything to database with setup patches.

2022-04-13 10:10 UTC, evktalo commented on src/registration.php
> + * See LICENSE_VAIMO.txt for license details.
LICENSE

2022-04-13 11:10 UTC, Nuuttif commented on CHANGELOG.md
> +- Support for Magento 2.4.4
Made these changes.

2022-04-13 11:10 UTC, Nuuttif commented on src/registration.php
> + * See LICENSE_VAIMO.txt for license details.
Made all the suggested changes.

2022-04-20 06:06 UTC, evktalo approved these changes

2022-05-03 07:18 UTC, merged